import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const wmSchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'projects',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'organization_id', type: 'string', isOptional: true },
        { name: 'code', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'phase', type: 'string', isOptional: true },
        { name: 'datum', type: 'string', isOptional: true },
        { name: 'progress', type: 'number' },
        { name: 'points', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'starts_on', type: 'string', isOptional: true },
        { name: 'ends_on', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'archived_at', type: 'string', isOptional: true },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'organizations',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'organization_type', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'country_code', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'archived_at', type: 'string', isOptional: true },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'contacts',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'organization_id', type: 'string', isOptional: true },
        { name: 'full_name', type: 'string' },
        { name: 'title', type: 'string', isOptional: true },
        { name: 'contact_type', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'last_contact_at', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'assets',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'asset_code', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'kind', type: 'string' },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'make', type: 'string', isOptional: true },
        { name: 'model', type: 'string', isOptional: true },
        { name: 'serial_number', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'purchase_date', type: 'string', isOptional: true },
        { name: 'purchase_cost', type: 'number', isOptional: true },
        { name: 'current_value', type: 'number', isOptional: true },
        { name: 'metadata', type: 'string' },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'archived_at', type: 'string', isOptional: true },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'asset_calibrations',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'asset_id', type: 'string' },
        { name: 'calibration_date', type: 'string' },
        { name: 'next_calibration_date', type: 'string', isOptional: true },
        { name: 'calibration_status', type: 'string' },
        { name: 'certificate_number', type: 'string', isOptional: true },
        { name: 'certificate_path', type: 'string', isOptional: true },
        { name: 'provider_name', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'asset_maintenance_events',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'asset_id', type: 'string' },
        { name: 'serviced_on', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'cost', type: 'number' },
        { name: 'provider_name', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'time_entries',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'user_id', type: 'string' },
        { name: 'project_id', type: 'string', isOptional: true },
        { name: 'entry_date', type: 'string' },
        { name: 'task', type: 'string' },
        { name: 'hours', type: 'number' },
        { name: 'billable', type: 'boolean' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'expense_entries',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'user_id', type: 'string' },
        { name: 'project_id', type: 'string', isOptional: true },
        { name: 'entry_date', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'vendor', type: 'string', isOptional: true },
        { name: 'reimbursable', type: 'boolean' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'jobs',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'project_id', type: 'string', isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'job_type', type: 'string', isOptional: true },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'scheduled_start', type: 'string', isOptional: true },
        { name: 'scheduled_end', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'archived_at', type: 'string', isOptional: true },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'job_events',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'project_id', type: 'string', isOptional: true },
        { name: 'job_id', type: 'string', isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'event_type', type: 'string', isOptional: true },
        { name: 'event_date', type: 'string' },
        { name: 'start_time', type: 'string', isOptional: true },
        { name: 'end_time', type: 'string', isOptional: true },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'job_assignments',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'project_id', type: 'string', isOptional: true },
        { name: 'job_id', type: 'string', isOptional: true },
        { name: 'assignment_date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'job_assignment_members',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'assignment_id', type: 'string' },
        { name: 'workspace_member_id', type: 'string' },
        { name: 'assignment_role', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'job_assignment_assets',
      columns: [
        { name: 'workspace_id', type: 'string' },
        { name: 'assignment_id', type: 'string' },
        { name: 'asset_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: '_deleted', type: 'boolean' },
      ],
    }),
  ],
})
